# Generated by Selenium IDE

import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestUntitled():
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.vars = {}
        self.driver.implicitly_wait(10)

    def teardown_method(self):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_untitled(self):
        self.driver.get("https://www.baidu.com/")
        self.driver.set_window_size(945, 542)
        self.driver.find_element(By.ID, "kw").click()
        self.driver.find_element(By.ID, "kw").send_keys("霍格沃兹测试学院")
        self.driver.find_element(By.ID, "su").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.LINK_TEXT, "霍格沃兹测试学院 – 测试开发工程师的黄埔军校").click()
        self.vars["win174"] = self.wait_for_window(2000)
        self.vars["root"] = self.driver.current_window_handle
        self.driver.switch_to.window(self.vars["win174"])
        self.driver.close()
        self.driver.switch_to.window(self.vars["root"])
        self.driver.close()
        self.driver.switch_to.window(self.vars["undefined"])


class TestWework:
    def test_demo(self):
        opt = webdriver.ChromeOptions()
        opt.debugger_address = "127.0.0.1:9222"
        driver = webdriver.Chrome(options=opt)
        driver.implicitly_wait(5)
        driver.get("")
        driver.find_element_by_id("").clear()

    def test_cookie(self):
        driver = webdriver.Chrome(options=opt)
        driver.implicitly_wait(5)

        driver.get("https://work.weixin.qq.com/wework_admin/loginpage_wx?")

        # cookies = driver.get_cookies()
        cookies = []
        for cookie in cookies:
            driver.add_cookie(cookie)

        driver.get("https://work.weixin.qq.com")
        driver.find_element_by_id("menu_constacts").click()

    def test_get_cookie(self):

        opt = webdriver.ChromeOptions()
        opt.debugger_address = "127.0.0.1:9222"
        driver = webdriver.Chrome(options=opt)
        driver.implicitly_wait(5)

        driver.get("https://work.weixin.qq.com")

        cookies = driver.get_cookies()